name: deploy
on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{hashFiles('package-lock.json')}}
          restore-keys: node_modules-
      - name: Install dependencies
        run: npm install --dev
      - run: |
          npm run build
          rm -rf /home/github-runner/deployments/todo-app-backend/
          cp -rv dist /home/github-runner/deployments/todo-app-backend/
          supervisorctl restart todo-app-backend
